name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - jupyter
  - notebook
  - ipykernel
  - pip:
    # ---- OS-Specific TensorFlow ----
    # Uncomment the section for your OS and comment out the other.

    # macOS (ARM - M1/M2/M3)
    - tensorflow-macos==2.13.0
    - tensorflow-metal==1.0.0

    # Linux / macOS (Intel) / Windows (Requires separate CUDA setup)
    # - tensorflow==2.13.0

    # ---- Common Dependencies ----
    - tensorflow-datasets==4.9.2
    - absl-py==1.4.0
    - anyio==4.0.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - array-record==0.4.0
    - arrow==1.3.0
    - asdfghjkl==0.1a2
    - astunparse==1.6.3
    - async-lru==2.0.4
    - attrs==23.1.0
    - babel==2.13.1
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - cachetools==5.3.1
    - certifi==2023.7.22
    - cffi==1.16.0
    - charset-normalizer==3.2.0
    - click==8.1.6
    - cmake==3.27.4.1
    - contourpy==1.1.0
    - cycler==0.11.0
    - defusedxml==0.7.1
    - dm-tree==0.1.8
    - einops==0.6.1
    - etils==1.4.1
    - exceptiongroup==1.1.3
    - fastjsonschema==2.18.1
    - filelock==3.12.4
    - flatbuffers==23.5.26
    - fonttools==4.42.0
    - fqdn==1.5.1
    - gast==0.4.0
    - google-auth==2.22.0
    - google-auth-oauthlib==1.0.0
    - google-pasta==0.2.0
    - googleapis-common-protos==1.60.0
    - grpcio==1.56.2
    - h5py==3.9.0
    - idna==3.4
    - imageio==2.32.0
    - importlib-metadata==6.8.0
    - importlib-resources==6.0.0
    - isoduration==20.11.0
    - jinja2==3.1.2
    - joblib==1.3.1
    - json5==0.9.14
    - jsonpointer==2.4
    - jsonschema==4.19.1
    - jsonschema-specifications==2023.7.1
    - jupyter-client==8.6.0
    - jupyter-events==0.9.0
    - jupyter-lsp==2.2.0
    - jupyter-server==2.10.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab==4.0.8
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.25.1
    - kaggle==1.5.16
    - keras==2.13.1
    - kiwisolver==1.4.4
    - lazy-loader==0.3
    - libclang==16.0.6
    - lit==16.0.6
    - markdown==3.4.4
    - markupsafe==2.1.3
    - matplotlib==3.7.2
    - mistune==3.0.2
    - mpmath==1.3.0
    - nbclient==0.9.0
    - nbconvert==7.11.0
    - nbformat==5.7.0
    - networkx==3.1
    - notebook==7.0.6
    - notebook-shim==0.2.3
    - np-utils==0.6.0
    - numpy==1.24.3
    - opencv-python==4.8.0.74
    - opt-einsum==3.3.0
    - overrides==7.4.0
    - pandas==2.0.3
    - pandocfilters==1.5.0
    - pillow==10.0.0
    - plotly==5.17.0
    - prometheus-client==0.18.0
    - promise==2.3
    - protobuf==4.23.4
    - pyasn1==0.5.0
    - pyasn1-modules==0.3.0
    - pycparser==2.21
    - pyparsing==3.0.9
    - python-json-logger==2.0.7
    - python-slugify==8.0.1
    - pytz==2023.3
    - pyyaml==6.0.1
    - referencing==0.30.2
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rpds-py==0.10.6
    - rsa==4.9
    - scikit-image==0.22.0
    - scikit-learn==1.3.0
    - scipy==1.11.1
    - seaborn==0.12.2
    - send2trash==1.8.2
    - sniffio==1.3.0
    - soupsieve==2.5
    - sympy==1.12
    - tenacity==8.2.2
    - tensorboard==2.13.0
    - tensorboard-data-server==0.7.1
    - tensorflow-estimator==2.13.0
    - tensorflow-io-gcs-filesystem==0.34.0
    - tensorflow-metadata==1.13.1
    - termcolor==2.3.0
    - terminado==0.18.0
    - text-unidecode==1.3
    - threadpoolctl==3.2.0
    - tifffile==2023.9.26
    - tinycss2==1.2.1
    - toml==0.10.2
    - tomli==2.0.1
    - tornado==6.3.3
    - tqdm==4.65.0
    # - triton==2.0.0 # Removed as it's likely not available/needed for macOS ARM
    - types-python-dateutil==2.8.19.14
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - unfoldnd==0.2.0
    - uri-template==1.3.0
    - urllib3==1.26.16
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.4
    - werkzeug==2.3.6
    - wget==3.2
    - wrapt==1.15.0
    - zipp==3.16.2
